trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'c4357bb4-fecd-4150-aa80-82656b0379c8'
  containerRegistry: 'octopetshoplab2026-f6cwffezbnddgmam.azurecr.io'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build, Push and Deploy

  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Images

    pool:
      vmImage: $(vmImageName)

    steps:

    # Database
    - task: Docker@2
      displayName: Build and push Database image
      inputs:
        command: buildAndPush
        repository: octopetshop-database
        dockerfile: '$(Build.SourcesDirectory)/OctopusSamples.OctoPetShop.Database/dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    # Product Service
    - task: Docker@2
      displayName: Build and push ProductService image
      inputs:
        command: buildAndPush
        repository: octopetshop-productservice
        dockerfile: '$(Build.SourcesDirectory)/OctopusSamples.OctoPetShop.ProductService/dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    # Shopping Cart Service
    - task: Docker@2
      displayName: Build and push ShoppingCartService image
      inputs:
        command: buildAndPush
        repository: octopetshop-shoppingcartservice
        dockerfile: '$(Build.SourcesDirectory)/OctopusSamples.OctoPetShop.ShoppingCartService/dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    # Web
    - task: Docker@2
      displayName: Build and push Web image
      inputs:
        command: buildAndPush
        repository: octopetshop-web
        dockerfile: '$(Build.SourcesDirectory)/OctopusSamples.OctoPetShop.Web/dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    # Create Octopus Release
    - task: OctopusCreateRelease@6
      name: create_release
      displayName: 'Create Octopus Release'
      inputs:
        OctoConnectedServiceName: 'Octopus'
        Space: 'Default'
        Project: 'OctoPetShop'
        ReleaseNumber: '$(Build.BuildId)'

    # Deploy Octopus Release
    - task: OctopusDeployRelease@6
      name: deploy_release
      displayName: 'Deploy Octopus Release'
      inputs:
        OctoConnectedServiceName: 'Octopus'
        Space: 'Default'
        Project: 'OctoPetShop'
        ReleaseNumber: '$(create_release.release_number)'
        Environment: 'Development'