apiVersion: batch/v1
kind: Job
metadata:
  name: octopetshop-dbup
spec:
  template:
    spec:
      containers:
        - name: dbup
          image: octopetshoplab2026-f6cwffezbnddgmam.azurecr.io/octopetshop-database:3
          #image: octopetshop_database
          #imagePullPolicy: Never
          command: [ "dotnet", "run", "--no-launch-profile" ]
          env:
            - name: DbUpConnectionString
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: connectionstring
      restartPolicy: Never

