apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopetshop-productservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: productservice
  template:
    metadata:
      labels:
        component: productservice
    spec:
      containers:
        - name: productservice
          image: octopetshoplab2026-f6cwffezbnddgmam.azurecr.io/octopetshop-productservice:#{ImageTag}
          #image: octopetshop_productservice
          #imagePullPolicy: Never
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5011"
              
            - name: OPSConnectionString
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: connectionstring
