apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopetshop-shoppingcartservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: shoppingcart
  template:
    metadata:
      labels:
        component: shoppingcart
    spec:
      containers:
        - name: shoppingcart
          #image: octopetshop_shoppingcartservice
          #imagePullPolicy: Never
          image: octopetshoplab2026-f6cwffezbnddgmam.azurecr.io/octopetshop-shoppingcartservice:#{ImageTag}
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5012"
              
            - name: OPSConnectionString
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: connectionstring
